name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: enhancedocs/enhancedocs-search
          path: enhancedocs-search
      - uses: enhancedocs/setup-enhancedocs@v0.1.3
        with:
          api-key: ${{ secrets.ENHANCEDOCS_API_KEY }}
      - name: Build EnhanceDocs
        run: enhancedocs build docs enhancedocs-search/lib
      - name: Install dependencies
        run: yarn install
      - name: Build website
        run: yarn run build
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: "./build"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
      - name: Publish EnhanceDocs
        run: enhancedocs push 642c2d009557653a6d46cdda
